require "yaml"

module LevelExporter
  struct FixturePlacementData
    property x : Int32
    property y : Int32
    property type_name : String
    def initialize(@x, @y, @type_name)
    end
  end

  struct DarkTowerSpawnData
    property x : Int32
    property y : Int32
    def initialize(@x, @y)
    end
  end

  struct TilePlacementData
    property x : Int32
    property y : Int32
    property type_name : String
    def initialize(@x, @y, @type_name)
    end
  end

  class ParsedLevel
    property id : Int32
    property map_width : Int32
    property map_height : Int32
    property player_spawn_x : Int32
    property player_spawn_y : Int32
    property initial_twilight : Float64
    property fixtures = [] of FixturePlacementData
    property spawns = [] of DarkTowerSpawnData
    property custom_tiles = [] of TilePlacementData

    def initialize(@id, @map_width, @map_height, @player_spawn_x, @player_spawn_y, @initial_twilight)
    end
  end

  def self.parse_level_file(file_path : String) : ParsedLevel
    content = File.read(file_path)
    data = YAML.parse(content)

    id = data["id"].as_i
    map_width = data["map_width"]?.try(&.as_i) || 60
    map_height = data["map_height"]?.try(&.as_i) || 30
    player_spawn_x = data["player_spawn"]["x"].as_i
    player_spawn_y = data["player_spawn"]["y"].as_i
    initial_twilight = data["initial_twilight"]?.try(&.as_f) || 0.9

    grid_raw = data["grid"].as_s
    lines = grid_raw.lines.map(&.chomp)

    if lines.size != map_height
      raise "Error in #{file_path}: grid has #{lines.size} lines, expected #{map_height}"
    end

    lines.each_with_index do |line, y|
      if line.size != map_width
        raise "Error in #{file_path}: line #{y} has length #{line.size}, expected #{map_width}"
      end
    end

    parsed = ParsedLevel.new(id, map_width, map_height, player_spawn_x, player_spawn_y, initial_twilight)

    visited = Array.new(map_height) { Array.new(map_width, false) }

    lines.each_with_index do |line, y|
      line.chars.each_with_index do |char, x|
        next if visited[y][x]

        case char
        when '.'
          visited[y][x] = true
        when '#'
          parsed.custom_tiles << TilePlacementData.new(x, y, "Wall")
          visited[y][x] = true
        when '~'
          parsed.custom_tiles << TilePlacementData.new(x, y, "Water")
          visited[y][x] = true
        when 'o'
          parsed.custom_tiles << TilePlacementData.new(x, y, "Stone")
          visited[y][x] = true
        when ','
          parsed.custom_tiles << TilePlacementData.new(x, y, "Dirt")
          visited[y][x] = true
        when 'P'
          parsed.fixtures << FixturePlacementData.new(x, y, "Pipe")
          visited[y][x] = true
        when 'R'
          check_footprint(file_path, lines, visited, x, y, 3, 3, 'R', "Refiner")
          parsed.fixtures << FixturePlacementData.new(x, y, "Refiner")
        when 'S'
          check_footprint(file_path, lines, visited, x, y, 2, 3, 'S', "Spire")
          parsed.fixtures << FixturePlacementData.new(x, y, "Spire")
        when 's'
          check_footprint(file_path, lines, visited, x, y, 3, 2, 's', "Seep")
          parsed.fixtures << FixturePlacementData.new(x, y, "Seep")
        when 'D'
          check_footprint(file_path, lines, visited, x, y, 3, 4, 'D', "DarkTower")
          parsed.spawns << DarkTowerSpawnData.new(x, y)
        else
          raise "Error in #{file_path}: unknown grid character '#{char}' at (#{x}, #{y})"
        end
      end
    end

    parsed
  end

  private def self.check_footprint(file_path : String, lines : Array(String), visited : Array(Array(Bool)), start_x : Int32, start_y : Int32, width : Int32, height : Int32, expected_char : Char, name : String)
    (0...height).each do |dy|
      (0...width).each do |dx|
        target_x = start_x + dx
        target_y = start_y + dy

        if target_y >= lines.size || target_x >= lines[target_y].size
          raise "Error in #{file_path}: #{name} footprint at (#{start_x}, #{start_y}) extends out of map bounds"
        end

        actual_char = lines[target_y][target_x]
        if actual_char != expected_char
          raise "Error in #{file_path}: #{name} at (#{start_x}, #{start_y}) expects '#{expected_char}' block of size #{width}x#{height}, but found '#{actual_char}' at (#{target_x}, #{target_y})"
        end

        visited[target_y][target_x] = true
      end
    end
  end

  def self.export_all(level_files : Array(String)) : String
    parsed_levels = level_files.map { |f| parse_level_file(f) }.sort_by(&.id)

    String.build do |str|
      str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
      str << "#pragma once\n\n"
      str << "#include <span>\n"
      str << "#include <array>\n"
      str << "#include \"alx/Levels.h\"\n\n"
      str << "namespace Assets {\n"
      str << "    namespace Levels {\n\n"

      parsed_levels.each do |lvl|
        id = lvl.id

        # Fixtures array
        if lvl.fixtures.empty?
          fixtures_expr = "{}"
        else
          str << "        constexpr alx::FixturePlacement k_level#{id}_fixtures[] = {\n"
          lvl.fixtures.each_with_index do |f, idx|
            comma = idx == lvl.fixtures.size - 1 ? "" : ","
            str << "            { {#{f.x}, #{f.y}}, alx::FixtureType::#{f.type_name} }#{comma}\n"
          end
          str << "        };\n\n"
          fixtures_expr = "k_level#{id}_fixtures"
        end

        # Dark Tower Spawns array
        if lvl.spawns.empty?
          spawns_expr = "{}"
        else
          str << "        constexpr alx::DarkTowerSpawn k_level#{id}_spawns[] = {\n"
          lvl.spawns.each_with_index do |s, idx|
            comma = idx == lvl.spawns.size - 1 ? "" : ","
            str << "            { {#{s.x}, #{s.y}} }#{comma}\n"
          end
          str << "        };\n\n"
          spawns_expr = "k_level#{id}_spawns"
        end

        # Custom tiles array
        if lvl.custom_tiles.empty?
          custom_tiles_expr = "{}"
        else
          str << "        constexpr alx::TilePlacement k_level#{id}_custom_tiles[] = {\n"
          lvl.custom_tiles.each_with_index do |t, idx|
            comma = idx == lvl.custom_tiles.size - 1 ? "" : ","
            str << "            { {#{t.x}, #{t.y}}, alx::TileType::#{t.type_name} }#{comma}\n"
          end
          str << "        };\n\n"
          custom_tiles_expr = "k_level#{id}_custom_tiles"
        end

        # Level struct
        str << "        inline const alx::Level k_level#{id} = {\n"
        str << "            .id                = #{lvl.id},\n"
        str << "            .map_width        = #{lvl.map_width},\n"
        str << "            .map_height       = #{lvl.map_height},\n"
        str << "            .player_spawn     = {#{lvl.player_spawn_x}, #{lvl.player_spawn_y}},\n"
        str << "            .initial_twilight = #{lvl.initial_twilight}f,\n"
        str << "            .fixtures         = #{fixtures_expr},\n"
        str << "            .dark_tower_spawns = #{spawns_expr},\n"
        str << "            .custom_tiles      = #{custom_tiles_expr}\n"
        str << "        };\n\n"
      end

      # ALL_LEVELS array
      str << "        inline const std::array<const alx::Level*, #{parsed_levels.size}> ALL_LEVELS = {\n"
      parsed_levels.each_with_index do |lvl, idx|
        comma = idx == parsed_levels.size - 1 ? "" : ","
        str << "            &k_level#{lvl.id}#{comma}\n"
      end
      str << "        };\n\n"

      # Helper lookup methods
      str << "        inline const alx::Level* get_level(int id) {\n"
      str << "            for (const alx::Level* lvl : ALL_LEVELS) {\n"
      str << "                if (lvl && lvl->id == id) return lvl;\n"
      str << "            }\n"
      str << "            return nullptr;\n"
      str << "        }\n\n"

      str << "        inline bool has_level(int id) {\n"
      str << "            return get_level(id) != nullptr;\n"
      str << "        }\n\n"

      str << "    } // namespace Levels\n"
      str << "} // namespace Assets\n"
    end
  end
end
