require "file_utils"
require "./export/fonts/font_txt"
require "./export/fonts/font_psf"
require "./export/music/music"
require "./export/images/image"

output_dir = "src/assets"
Dir.mkdir_p(output_dir) unless Dir.exists?(output_dir)

# Parse optional filter flag (e.g. --only=fonts, --only=images, --only=music)
target_filter = nil
ARGV.each do |arg|
  if arg.starts_with?("--only=")
    target_filter = arg.split("=").last.downcase
  end
end

puts "==> Packing Game Asset#{target_filter ? " [Filter: #{target_filter.capitalize}]" : ""}..."

# Helper check to see if a category should run
def should_run?(category : String, filter : String?)
  return true if filter.nil?
  filter == category.downcase
end

# -------------------------------------------------------------
# FONTS -> src/assets/Fonts.h
# -------------------------------------------------------------
if should_run?("fonts", target_filter)
  font_files = Dir.glob("assets/fonts/*.txt") + Dir.glob("assets/fonts/*.psf")
  if font_files.any?
    fonts_header = String.build do |str|
      str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
      str << "#pragma once\n\n"
      str << "#include \"core/Font.h\"\n\n"
      str << "namespace Assets {\n"
      str << "    namespace Fonts {\n\n"

      font_files.each do |file_path|
        ext = File.extname(file_path).downcase
        case ext
        when ".txt"
          puts "  [Font]  #{file_path}"
          str << FontTxtExporter.export(file_path)
        when ".psf"
          puts "  [Font]  #{file_path}"
          str << FontPsfExporter.export(file_path)
        end
      end

      str << "    }\n"
      str << "}\n"
    end

    File.write(File.join(output_dir, "Fonts.h"), fonts_header)
    puts "Generated -> src/assets/Fonts.h"
  end
end

# -------------------------------------------------------------
# IMAGES -> src/assets/Images.h
# -------------------------------------------------------------
if should_run?("images", target_filter)
  image_files = Dir.glob("assets/images/*.aseprite")
  if image_files.any?
    # Check for dedicated master palette file (e.g. assets/images/palette.aseprite)
    master_palette_file = image_files.find { |f| File.basename(f).downcase.starts_with?("palette") }

    # Exclude master palette file and any files starting with '_' from sprite array generation
    sprite_files = image_files.reject do |f|
      f == master_palette_file || File.basename(f).starts_with?("_")
    end

    gpl_file = "assets/images/palette.gpl"
    gpl_palette = [] of String

    if File.exists?(gpl_file)
      puts "  [Palette] Direct parsing master GPL palette: #{gpl_file}"
      File.each_line(gpl_file) do |line|
        # Skip GPL header lines and comments
        next if line.starts_with?("GIMP") || line.starts_with?("Channels:") || line.starts_with?("Name:") || line.starts_with?("Columns:") || line.starts_with?("#") || line.strip.empty?
        # Aseprite GPL format: "  R   G   B  A\tLabel" - split on whitespace, take first 4 numeric tokens
        parts = line.split.select { |p| p =~ /^\d+$/ }
        if parts.size >= 4
          # R G B A
          gpl_palette << "0x%02X%02X%02X%02X" % {parts[3].to_i, parts[0].to_i, parts[1].to_i, parts[2].to_i}
        elsif parts.size >= 3
          # R G B (no alpha)
          gpl_palette << "0xFF%02X%02X%02X" % {parts[0].to_i, parts[1].to_i, parts[2].to_i}
        end
      end
    end

    processed_sprites = [] of ImageExporter::SpriteData

    # Process master palette file if present to seed GLOBAL_PALETTE
    master_sprite = master_palette_file ? ImageExporter.process_sprite(master_palette_file) : nil

    sprite_files.each do |file_path|
      puts "  [Image] #{file_path}"
      processed_sprites << ImageExporter.process_sprite(file_path, gpl_file)
    end

    images_header = String.build do |str|
      str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
      str << "#pragma once\n\n"
      str << "#include <cstddef>\n"
      str << "#include <cstdint>\n\n"
      str << "namespace Assets {\n"
      str << "    namespace Images {\n\n"

      str << "        struct FrameDescriptor {\n"
      str << "            size_t offset;\n"
      str << "            size_t len;\n"
      str << "            uint16_t width;\n"
      str << "            uint16_t height;\n"
      str << "            uint16_t duration_ms;\n"
      str << "        };\n\n"

      str << "        struct TagDescriptor {\n"
      str << "            const char* name;\n"
      str << "            uint16_t from_frame;\n"
      str << "            uint16_t to_frame;\n"
      str << "            bool loop;\n"
      str << "        };\n\n"

      global_palette = Array(String).new(256, "0x00FF00FF") # Default padding with magenta transparency

      if gpl_palette.any?
        gpl_palette.each_with_index do |color, idx|
          global_palette[idx] = color if idx < 256
        end
      elsif master_sprite
        puts "  [Palette] Using master palette from #{master_palette_file}"
        master_sprite.palette.each_with_index do |color, idx|
          global_palette[idx] = color if idx < 256
        end
      end

      # Merge any additional palette entries from sprite files if not set by master
      processed_sprites.each do |sprite|
        sprite.palette.each_with_index do |color, idx|
          if idx < 256 && global_palette[idx] == "0x00FF00FF"
            global_palette[idx] = color
          end
        end
      end

      str << "        inline const uint32_t GLOBAL_PALETTE[256] = {\n"
      global_palette.each_slice(8) do |chunk|
        str << "            " << chunk.join(", ") << ",\n"
      end
      str << "        };\n\n"

      # Export individual RLE arrays and descriptors (excluding master_palette_file)
      processed_sprites.each do |sprite|
        str << "        inline const uint16_t #{sprite.name}_width = #{sprite.width};\n"
        str << "        inline const uint16_t #{sprite.name}_height = #{sprite.height};\n"
        str << "        inline const size_t #{sprite.name}_len = #{sprite.compressed_size};\n"
        str << "        inline const uint8_t #{sprite.name}[#{sprite.compressed_size}] = {\n"
        str << "            " << sprite.c_array_string << "\n"
        str << "        };\n\n"

        str << "        inline const FrameDescriptor #{sprite.name}_frames[#{sprite.frames.size}] = {\n"
        sprite.frames.each do |f|
          str << "            { #{f.offset}, #{f.len}, #{f.width}, #{f.height}, #{f.duration_ms} },\n"
        end
        str << "        };\n\n"

        str << "        inline const TagDescriptor #{sprite.name}_anims[#{sprite.tags.size}] = {\n"
        sprite.tags.each do |t|
          str << "            { \"#{t.name}\", #{t.from_frame}, #{t.to_frame}, #{t.loop ? "true" : "false"} },\n"
        end
        str << "        };\n\n"
      end

      str << "    }\n"
      str << "}\n"
    end

    File.write(File.join(output_dir, "Images.h"), images_header)
    puts "Generated -> src/assets/Images.h"
  end
end


# -------------------------------------------------------------
# MUSIC -> src/assets/Music.h
# -------------------------------------------------------------
if should_run?("music", target_filter)
  music_files = Dir.glob("assets/music/*.mod")
  if music_files.any?
    music_header = String.build do |str|
      str << "// Auto-generated by pack_assets.cr - DO NOT EDIT MANUALLY\n"
      str << "#pragma once\n\n"
      str << "#include <cstddef>\n"
      str << "#include <cstdint>\n\n"
      str << "namespace Assets {\n"
      str << "    namespace Music {\n"

      music_files.each do |file_path|
        puts "  [Music] #{file_path}"
        str << MusicExporter.export(file_path)
      end

      str << "    }\n"
      str << "}\n"
    end

    File.write(File.join(output_dir, "Music.h"), music_header)
    puts "Generated -> src/assets/Music.h"
  end
end

puts "==> All asset packs updated successfully!"
